/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Sun Oct  9 14:08:08 2016. */

#include "sensor.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t IMUData_fields[11] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, IMUData, ax, ax, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, IMUData, ay, ax, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, IMUData, az, ay, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, IMUData, gx, az, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, IMUData, gy, gx, 0),
    PB_FIELD(  6, INT32   , REQUIRED, STATIC  , OTHER, IMUData, gz, gy, 0),
    PB_FIELD(  7, FLOAT   , REQUIRED, STATIC  , OTHER, IMUData, yaw, gz, 0),
    PB_FIELD(  8, FLOAT   , REQUIRED, STATIC  , OTHER, IMUData, pitch, yaw, 0),
    PB_FIELD(  9, FLOAT   , REQUIRED, STATIC  , OTHER, IMUData, roll, pitch, 0),
    PB_FIELD( 10, INT32   , REQUIRED, STATIC  , OTHER, IMUData, temperature, roll, 0),
    PB_LAST_FIELD
};

const pb_field_t FootSensorData_fields[2] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, FootSensorData, imu_data, imu_data, &IMUData_fields),
    PB_LAST_FIELD
};

const pb_field_t SensorData_fields[3] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, SensorData, left, left, &FootSensorData_fields),
    PB_FIELD(  2, MESSAGE , REQUIRED, STATIC  , OTHER, SensorData, right, left, &FootSensorData_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(FootSensorData, imu_data) < 65536 && pb_membersize(SensorData, left) < 65536 && pb_membersize(SensorData, right) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_IMUData_FootSensorData_SensorData)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(FootSensorData, imu_data) < 256 && pb_membersize(SensorData, left) < 256 && pb_membersize(SensorData, right) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_IMUData_FootSensorData_SensorData)
#endif


/* @@protoc_insertion_point(eof) */
